version: "3.8"
services:
  db:
    build: ./docker/mysql
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - db-store:/var/lib/mysql

  web:
    image: nginx:1.18-alpine
    ports:
      - 8000:8000
    volumes :
      - ./src:/workspace
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/uwsgi_params:/etc/nginx/uwsgi_params
    working_dir:
      /workspace
    depends_on:
      - app

  app:
      build: ./docker/python
      command: uwsgi --socket :8001 --module app.wsgi --py-autoreload 1 --logto /tmp/tmp.log
      volumes:
        - ./src:/workspace
      expose:
        - "8001"
      depends_on:
        - db

volumes:
  db-store:
